server:
  port: 31001
  #context-path:
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  freemarker:
    cache: false # 关闭模板缓存
    settings:
      template_update_delay:  0

